title: ThunderNL's game list
description: List of games I have played or want to play.
theme: just-the-docs

url: https://thundernl.github.io/gamelist

aux_links:
  Template Repository: https://github.com/thundernl/gamelist
